site_name: My Project
nav:
  - Home: index.md
  - API:
      - PressureLogarithmic: plog.md
      - FallOff: falloff.md
      - CABR: cabr.md
plugins:
  - search
  - mkdocstrings
theme:
  name: "material"
